dz3-2 accordion
js-tasks-ru/htmlcss-20220919_kuzya9 pull request #6
Opened 2022-10-01 16:33 UTC by UnderAway

2022-10-01 16:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-02 19:46 UTC, GSemikozov requested changes

2022-10-02 19:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 8px;
надо только снизу

2022-10-02 19:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
если глобальные сбросы - унесем в normalize, если конкретно в рамках компонента - тогда используем классы по БЭМ

2022-10-02 19:46 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details open class="accordion__item">
элементы блока не могут существовать вне своего блока, поэтому - надо завернуть все элементы в div с классом accordion

2022-10-03 08:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 10:11 UTC, GSemikozov approved these changes

2022-10-03 10:11 UTC, merged