histograma
js-tasks-ru/htmlcss-20220919_kuzya9 pull request #8
Opened 2022-10-12 15:48 UTC by UnderAway

2022-10-12 15:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 20:45 UTC, GSemikozov requested changes

2022-10-12 20:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
высоту и ширину жестко фиксировать не надо, это будет лишним

2022-10-12 20:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header > p {
вложенные селекторы и селекторы тегов в БЭМ не используем (должен быть класс)

2022-10-12 20:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border: solid 1px var(--grey-3);
не хватает общих паддингов (чтобы потом не задавать одинаковые паддинги у всех дочерних элементов)

2022-10-12 20:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: center;
лишнее

2022-10-12 20:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 39px 24px 24px 26px;
по таким отступам см выше

2022-10-13 19:17 UTC, GSemikozov approved these changes

2022-10-13 19:18 UTC, merged